[project]
name = 'stacks-nft-staking'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.public-mint-nft-v3]
path = 'contracts/public-mint-nft-v3.clar'
clarity_version = 2
epoch = '2.1'

[contracts.reward-token-v3]
path = 'contracts/reward-token-v3.clar'
clarity_version = 2
epoch = '2.1'

[contracts.stake-nft-v3]
path = 'contracts/stake-nft-v3.clar'
clarity_version = 2
epoch = '2.1'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
